# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d22db79608a50df4e9869056bee49f54bcdb8d10a4b0550751d7afa07eb567b1091ec2ea334ca9c89c1652d28f36bf7936da059c47376d6f637ae6967edc9885

test:
  secret_key_base: ecbc6ae98547a42d3a92fea7d4e486684149d5ba5e37a2ed248539d531fb396cf6373e069b0699523ff935dd7c2e4d917a4700e9d95129ec661a8e60e58c9986

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
